/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:36e828bd-41f4-43ec-80ef-dae9378bcfad",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PfVyF4db5",
    "aws_user_pools_web_client_id": "5jv9msotdasgn7oribk2his4at",
    "oauth": {},
    "aws_user_files_s3_bucket": "borderradius4bd0ffa18a7a43bc90150ec6ec457e05174354-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
